<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ubuntu" failures="1" tests="5" name="Suite1Tests" time="0.035" errors="0" timestamp="2025-01-22T22:46:54 IST">
  <testcase classname="com.example.suite1.Suite1Tests" name="failingTest1" time="0.004">
    <failure type="java.lang.AssertionError" message="This test is designed to fail.">
      <![CDATA[java.lang.AssertionError: This test is designed to fail.
at com.example.suite1.Suite1Tests.failingTest1(Suite1Tests.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- failingTest1 -->
  <testcase classname="com.example.suite1.Suite1Tests" name="passingTest1" time="0.0"/>
  <testcase classname="com.example.suite1.Suite1Tests" name="passingTest2" time="0.001"/>
  <testcase classname="com.example.suite1.Suite1Tests" name="skippedTest1" time="0.001">
    <skipped/>
  </testcase> <!-- skippedTest1 -->
  <testcase classname="com.example.suite1.Suite1Tests" name="dependentTest1" time="0.0">
    <skipped/>
  </testcase> <!-- dependentTest1 -->
</testsuite> <!-- Suite1Tests -->
